spring:
  datasource:
    url: jdbc:h2:mem:bank_application_test_task
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update