spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_application_test_task
    username: #username
    password: #password
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update